### ISSUE TITLE
请问一下数据问题

### ISSUE THREAD

**Issue by maximus-1024** [yuyeqianxun/vue-cart#1]
这个写的真是太好了，请教一下一般数据都是后台给的，里面一般都是选中状态和每个商量的商品数量和选中的商品数量的 这个怎么处理起来比较好呢 谢谢

**Comment by yuyeqianxun** [comment]
抱歉回复晚了，关于你提到的商品选中状态和数量问题，不同的公司有不同的处理。我参考了京东的购物车，它是多个端同步的，说明商品的选中状态和数量都是会存入数据库的，这种情况让后端给你加字段。如果你公司购物车数据不需要多端同步，那你对后台数据处理下，前端加入字段后再赋值给购物车数据

**Comment by yuyeqianxun** [comment]
@liwei1991 抱歉回复晚了，关于你提到的商品选中状态和数量问题，不同的公司有不同的处理。我参考了京东的购物车，它是多个端同步的，说明商品的选中状态和数量都是会存入数据库的，这种情况让后端给你加字段。如果你公司购物车数据不需要多端同步，那你对后台数据处理下，前端加入字段后再赋值给购物车数据

**Comment by maximus-1024** [comment]
好的。多谢了，我这个需求，购物车还有分页加载更多类似淘宝，全选状态，和删除购物车的商品 我还是觉得挺麻烦的
